### ISSUE TITLE
Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by bernardotavares** [rpsimao/invoicexpress-api#1]
Hey, congrats for the package.
I would like to use it in a laravel 5.5 project, but altough the README states `Tested with Laravel 5.5.*`, the [composer requires laravel/framework 5.8.*](https://github.com/rpsimao/invoicexpress-api/blob/master/composer.json) and [previous versions of the package jump from 5.4 to 5.7](https://packagist.org/packages/rpsimao/invoicexpress-api)

I can still force the installation, but wanted to understand if there is any reason for this and what would be the best version to use with 5.5?

Thank you!

**Comment by rpsimao** [comment]
Hi Bernardo 
To be honest can’t remember why I did that in composer.
But I’m pretty sure that it’ll work with 5.5. 
I don’t recall doing any changes in the code.
Nevertheless just run the tests.

Any help, just let me know.

**Comment by bernardotavares** [comment]
Laravel 5.5 don't have LTS anymore so it's not too important to have it the original project.

But in case someone needs this, I did a fork just to sort the issue temporarily
[https://github.com/bernardotavares/invoicexpress](https://github.com/bernardotavares/invoicexpress)

I have been using with 5.5 with no problems for some months now.

The require in composer.json neeeds to be a bit different

```
"require": {
        "indigit/invoicexpress": "dev-master",
        "ext-curl": "*",
        "ext-json": "*",
        "fortis/iso-currency": "^1.0",
        "guzzlehttp/guzzle": "~6.0"
    },
    "repositories": [
        {
            "_comment_info": "The original indigit/invoicexpress requires laravel 5.8 so we forked it and made it compatible with 5.5",
            "_comment_dependencies": "ext-curl, ext-json, fortis/iso-currency and guzzlehttp/guzzle dependencies cannot be loaded recursively using this method, so they were added to this plugin required packages",
            "type": "package",
            "package": {
                "name": "indigit/invoicexpress",
                "version": "dev-master",
                "source": {
                    "url": "https://github.com/bernardotavares/invoicexpress.git",
                    "type": "git",
                    "reference": "master"
                },
                "autoload": {
                    "classmap": [
                        ""
                    ]
                }
            }
        }
    ]
```
